Resources:
  ReceiveMailTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: postbox-mail-received-${opt:stage}
      KmsMasterKeyId: alias/aws/sns

  ReceiveMailTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref ReceiveMailTopic
      PolicyDocument: |
        {
          "Version": "2012-10-17",
          "Id": "__default_policy_ID",
          "Statement": [
            {
              "Sid": "__default_statement_ID",
              "Effect": "Allow",
              "Principal": {
                "AWS": "*"
              },
              "Action": [
                "SNS:Subscribe",
                "SNS:SetTopicAttributes",
                "SNS:RemovePermission",
                "SNS:Receive",
                "SNS:Publish",
                "SNS:ListSubscriptionsByTopic",
                "SNS:GetTopicAttributes",
                "SNS:DeleteTopic",
                "SNS:AddPermission"
              ],
              "Resource": "arn:aws:sns:us-east-1:${aws:accountId}:postbox-mail-received-${opt:stage}",
              "Condition": {
                "StringEquals": {
                  "AWS:SourceOwner": "${aws:accountId}"
                }
              }
            }
          ]
        }